Tracker:AddLayouts("layouts/settings_popup.jsonc")
Tracker:AddLayouts("layouts/settings_tab.jsonc")
Tracker:AddLayouts("layouts/weapon_barrier_settings_tab.jsonc")
Tracker:AddLayouts("layouts/inventory.jsonc")
Tracker:AddLayouts("layouts/weapons.jsonc")

Tracker:AddLayouts("layouts/tracker.jsonc")
Tracker:AddLayouts("layouts/level_1.jsonc")
Tracker:AddLayouts("layouts/level_2.jsonc")
--Tracker:AddLayouts("layouts/level_3.jsonc")
--Tracker:AddLayouts("layouts/level_4.jsonc")
--Tracker:AddLayouts("layouts/level_5.jsonc")
--Tracker:AddLayouts("layouts/level_6.jsonc")