Tracker:AddLocations("locations/Hub.jsonc")

Tracker:AddLocations("locations/1-1.jsonc")
Tracker:AddLocations("locations/1-2.jsonc")
Tracker:AddLocations("locations/1-3.jsonc")
Tracker:AddLocations("locations/1-4.jsonc")
Tracker:AddLocations("locations/1-5.jsonc")
Tracker:AddLocations("locations/1-6.jsonc")
Tracker:AddLocations("locations/1-7.jsonc")
Tracker:AddLocations("locations/1-8.jsonc")
Tracker:AddLocations("locations/1-9.jsonc")
Tracker:AddLocations("locations/1-O.jsonc")

--Tracker:AddLocations("locations/2-1.jsonc")
--Tracker:AddLocations("locations/2-2.jsonc")
--Tracker:AddLocations("locations/2-3.jsonc")
--Tracker:AddLocations("locations/2-4.jsonc")
--Tracker:AddLocations("locations/2-5.jsonc")
--Tracker:AddLocations("locations/2-6.jsonc")
--Tracker:AddLocations("locations/2-7.jsonc")
--Tracker:AddLocations("locations/2-8.jsonc")
--Tracker:AddLocations("locations/2-GY1.jsonc")
--Tracker:AddLocations("locations/2-GY2.jsonc")
--Tracker:AddLocations("locations/2-GY3.jsonc")
--Tracker:AddLocations("locations/2-O.jsonc")