Tracker:AddLocations("locations/Hub.jsonc")

Tracker:AddLocations("locations/level_1/1-1.jsonc")
Tracker:AddLocations("locations/level_1/1-2a.jsonc")
Tracker:AddLocations("locations/level_1/1-3.jsonc")
Tracker:AddLocations("locations/level_1/1-2b.jsonc")
Tracker:AddLocations("locations/level_1/1-4.jsonc")
Tracker:AddLocations("locations/level_1/1-5.jsonc")
Tracker:AddLocations("locations/level_1/1-6.jsonc")
Tracker:AddLocations("locations/level_1/1-7.jsonc")
Tracker:AddLocations("locations/level_1/1-8.jsonc")
Tracker:AddLocations("locations/level_1/1-9.jsonc")
Tracker:AddLocations("locations/level_1/1-O.jsonc")

Tracker:AddLocations("locations/level_2/2-1.jsonc")
Tracker:AddLocations("locations/level_2/2-2.jsonc")
Tracker:AddLocations("locations/level_2/2-3.jsonc")
Tracker:AddLocations("locations/level_2/2-4.jsonc")
Tracker:AddLocations("locations/level_2/2-O.jsonc")
Tracker:AddLocations("locations/level_2/2-5.jsonc")
Tracker:AddLocations("locations/level_2/2-6a.jsonc")
Tracker:AddLocations("locations/level_2/2-6b.jsonc")
Tracker:AddLocations("locations/level_2/2-GY1.jsonc")
Tracker:AddLocations("locations/level_2/2-6c.jsonc")
Tracker:AddLocations("locations/level_2/2-7.jsonc")
Tracker:AddLocations("locations/level_2/2-GY2.jsonc")
Tracker:AddLocations("locations/level_2/2-8.jsonc")
Tracker:AddLocations("locations/level_2/2-GY3.jsonc")